spring:
  h2.console:
    enabled: true
    path: "/h2-console"

  datasource:
    url: "jdbc:h2:mem:bookstoredb"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: "create-drop"
    show_sql: true
    properties.hibernate.format_sql: true

logging.level:
  org.hibernate:
    type: trace

pricing:
  discount:
    default-minimum-copies: 3
    regular:
      bundle: 0.9
    old-edition:
      default: 0.8
      bundle: 0.95
