openapi: 3.0.4
info:
  title: Online Bookstore API
  version: 0.0.1-SNAPSHOT
  description: |-
    The Online Bookstore API provides a robust platform for managing an online book retail system.
    
    It handles book inventory management, enabling seamless tracking and updating of book stock.
    
    The API supports purchase processing and dynamic book pricing, ensuring accurate transactions and 
    flexible pricing strategies. 
    
    Additionally, it manages customer loyalty points, rewarding repeat customers with points for purchases, 
    which can be redeemed for discounts or perks, enhancing user engagement and retention.
  contact:
    email: pedraza.miguez@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
    description: Local server
tags:
  - name: customer
    description: Customer operations and loyalty points consultation
  - name: book
    description: Books and inventory management
  - name: purchase
    description: Purchase processing and order management
paths:
  /v1/books/{bookId}:
    get:
      tags:
        - book
      summary: Get book details by ID
      description: Get book details by ID
      operationId: getBookById
      parameters:
        - name: bookId
          in: path
          description: ID of the book to retrieve
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
          example: 178
      responses:
        '200':
          description: Book details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Invalid ID supplied
        '404':
          description: Book not found
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bookstore_auth:
            - read:books
  /v1/books:
    post:
      tags:
        - book
      summary: Add a new book
      description: Add a new book to the bookstore
      operationId: addBook
      requestBody:
        $ref: '#/components/requestBodies/Book'
      responses:
        '201':
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Book structure is malformed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: "BAD_REQUEST"
                message: "author: must not be null"
                path: "uri=/v1/books"
                timestamp: "2025-04-18T16:19:34.714622"
        '409':
          description: Book already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: "CONFLICT"
                message: "A book with ISBN 1234567890 already exists"
                path: "uri=/v1/books"
                timestamp: "2025-04-18T16:19:34.714622"
        '422':
          description: Book structure is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: "UNPROCESSABLE_ENTITY"
                message: "Book price must be greater than zero"
                path: "uri=/v1/books"
                timestamp: "2025-04-18T16:19:34.714622"
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: "INTERNAL_SERVER_ERROR"
                message: "An unexpected error occurred"
                path: "uri=/v1/books"
                timestamp: "2025-04-18T16:19:34.714622"
      security:
        - bookstore_auth:
            - write:books
            - read:books
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 178
        title:
          type: string
          example: "Effective Java"
        author:
          type: string
          example: "Joshua Bloch"
        genre:
          type: string
          description: Genre of the book
          enum:
            - FICTION
            - NON_FICTION
            - MYSTERY
            - FANTASY
            - SCIENCE_FICTION
            - BIOGRAPHY
            - HISTORY
            - ROMANCE
            - THRILLER
            - CHILDREN
    BookRequest:
      required:
        - isbn
        - title
        - author
        - publisher
        - year
        - price
        - genre
        - type
      type: object
      properties:
        isbn:
          type: string
          description: ISBN of the book
          example: "978-3-16-148410-0"
        title:
          type: string
          description: Title of the book
          example: "Effective Java"
        author:
          type: string
          description: Author of the book
          example: "Joshua Bloch"
        publisher:
          type: string
          description: Publisher of the book
          example: "Addison-Wesley"
        year:
          type: integer
          description: Year of publication
          example: 2008
        price:
          type: string
          format: decimal
          description: Price of the book
          example: "21.99"
        genre:
          type: string
          description: Genre of the book
          enum:
            - FICTION
            - NON_FICTION
            - MYSTERY
            - FANTASY
            - SCIENCE_FICTION
            - BIOGRAPHY
            - HISTORY
            - ROMANCE
            - THRILLER
            - CHILDREN
        type:
          type: string
          description: Type of the book
          enum:
            - NEW_RELEASE
            - REGULAR
            - OLD_EDITION
    Error:
      type: object
      properties:
        status:
          type: string
          description: HTTP status constant
        message:
          type: string
          description: Error message
        path:
          type: string
          description: Path of the request
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the error
  requestBodies:
    Book:
      description: Book object that needs to be added to the store
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BookRequest'
  securitySchemes:
    bookstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://localhost/oauth2/authorize
          scopes:
            "write:books": modify books
            "read:books": read books
    api_key:
      type: apiKey
      name: api_key
      in: header
