name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Disable shallow clone for better SonarQube analysis relevancy

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.7'
          distribution: 'temurin'  # Use Eclipse Temurin distribution for Java 21

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('online-bookstore/pom.xml') }}
          restore-keys: ${{ runner.os }}-sonar-

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('online-bookstore/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build and analyze with SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # SonarQube authentication token
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # Your SonarQube instance URL
        working-directory: online-bookstore  # Set working directory to the folder containing pom.xml
        run: |
          mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=Online-Bookstore \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
